[
            {name: 'Anil', billable: true, projects: ['PDX'], organization: 'Baratheon'},
            {name: 'Preshit', billable: true, projects: ['CMS'], organization: 'Targareyen'},
            {name: 'Sumeet', billable: true, projects: ['Loven'], organization: 'Starks'},
            {name: 'Anuja', billable: true, projects: ['Loven'], organization: 'Starks'},
            {name: 'Vijay', billable: true, projects: ['Loven'], organization: 'Starks'},
            {name: 'Sourabh', billable: false, projects: ['LRS', 'Zimbra'], organization: 'Lanisters'},
            {name: 'Rohan', billable: true, projects: ['LRS'], organization: 'Lanisters'},
            {name: 'Atul', billable: true, projects: ['Google'], organization: 'Synerzip'},
            {name: 'Uttam', billable: true, projects: ['Google'], organization: 'Synerzip'},
            { name: 'Rahul', billable: true, projects: ['Google'], organization: 'Synerzip'},
            { name: 'Salil', billable: true, projects: ['Google'], organization: 'Synerzip'},
            { name: 'Praveen', billable: true, projects: ['Mercatus'], organization: 'Lanisters'},
            { name: 'Ashutosh', billable: true, projects: ['Mercatus'], organization: 'Lanisters'},
            { name: 'Mitesh', billable: true, projects: ['Mercatus'], organization: 'Lanisters'},
            { name: 'Chandan', billable: true, projects: ['Mercatus'], organization: 'Lanisters'},
            { name: 'Amol', billable: false, projects: ['Mercatus'], organization: 'Lanisters'},
            { name: 'Mukund', billable: true, projects: ['Halliburton'], organization: 'Starks'},
            { name: 'Onkar', billable: true, projects: ['Halliburton'], organization: 'Starks'},
            { name: 'Preshit', billable: true, projects: ['Studer'], organization: 'Targareyen'},
            { name: 'Hrishikesh', billable: true, projects: ['Zimbra'], organization: 'Lanisters'},
            { name: 'Rane', billable: true, projects: ['Zimbra'], organization: 'Lanisters'},
            { name: 'Rohit', billable: true, projects: ['CloudOn', 'Prezi'], organization: 'Tryrell'},
            { name: 'Sujit', billable: true, projects: ['CloudOn'], organization: 'Tryrell'},
            { name: 'Amit Bakore', billable: true, projects: ['CloudOn'], organization: 'Tryrell'},
            { name: 'Ravindra', billable: true, projects: ['Prezi'], organization: 'Tryrell'},
            { name: 'Amit', billable: true, projects: ['Prezi'], organization: 'Tryrell'},
            { name: 'Anand', billable: false, projects: ['PDX'], organization: 'Baratheon'},
            { name: 'Vinayak', billable: false, projects: ['PDX', 'Google', 'Mercatus', 'LRS', 'CloudOn'], organization: 'Synerzip'},
            { name: 'Hemant', billable: false, projects: ['CMS', 'Loven', 'Halliburton', 'Zimbra', 'Studer', 'Prezi'], organization: 'Synerzip'},
            { name: 'Anant', billable: false, organization: 'Synerzip'},
            { name: 'Sandeep', billable: false, projects: ['Loven'], organization: 'Starks'},
            { name: 'Prakash', billable: false, organization: 'Lanisters'},
            { name: 'Jeevan', billable: false, projects: ['Studer'], organization: 'Targareyen'},
            { name: 'Rajesh', billable: false, projects: [], organization: 'Tryrell'},
            { name: 'Pavan', billable: false, projects: ['CloudOn'], organization: 'Tryrell'},
            { name: 'Sachin', billable: false, projects: ['Google'], organization: 'Synerzip'}
        ]
